### ISSUE TITLE
Crashing or freezing when using search

### ISSUE THREAD

**Issue by Salamander-E** [donkeyProgramming/TheAssetEditor#128]
With a lot of search entries, especially when the term is quite broad, the editor automatically expands loads of folders containing the term. I believe this is causing huge lag and sometimes the app crashes.

**Comment by Pear-231** [comment]
Cheers for the report. Can you give an example of a specific term you're searching?

**Comment by Salamander-E** [comment]
I'm struggling to recreate it now, maybe it was just an issue I brought about myself having been exploring vanilla assets for a while editing a couple of my own packfiles.

Was just simple stuff like "Kroxi" and "Warlock".

FYI it's running smooth as butter and not expanding folders now I'm trying to make it! Sorry for the seeming false alarm.
________________________________

**Comment by donkeyProgramming** [comment]
Searching for XML is a good way to make it crash. Its a know bug.
The problem is that the tree view does not handle the amount of items. Solving this is probably a fairly hard issue. 

Suggestion for workaround: 
If the number of resulted files from search is larger then x (maybe 500?) give a error message saying that the search it to broad. While not great, at least it will not crash the tool

**Comment by donkeyProgramming** [comment]
Improved for next release
